### ISSUE TITLE
The Nimble executable could not be found.

### ISSUE THREAD

**Issue by partisanyc** [Varriount/NimLime#62] opened 2016-02-20 05:44 UTC
Hi, 

On Ubuntu 14.04, I've installed Nim 0.13.0, nimble 0.7.0 and am attempting to use NimLime on Sublime Text 3 installed through Package Control. I added the nim bin directory and the nimble root directory to PATH in my .bashrc and restarted. When I start Sublime, I get three pop-ups, each indicating that Nimble, Nim, and Nimsuggest executables could not be found, even though nim and nimble are in the PATH. I've tried setting the explicit paths in User settings, but that did not work either. 

When I run Setup Nimsuggest, it says "Compiling Internal Nimsuggest...", but never changes and it does not produce output either to the home directory or to another existing directory I've tried. 

Any ideas?

**Comment by partisanyc** [comment] 2016-02-20 06:15
Sorry, I should have just installed through apt-get. The issue was that the path in Sublime was wrong. Once I used the "subl" command from terminal, I get much further. The current issue is with Setup Nimsuggest. 

It says 

> No such file or directory: '/tmp/tmpqj98a4/nimsuggest/nimsuggest'

The directory /tmp/tmpqj98a4/nimsuggest does exist, but nimsuggest doesn't appear to be in the folder, only nim sources, so maybe it hasn't been compiled? Here is the ouput from console:

`Please look at the output of the debug console (ctrl+``) for more information.
error: Nimsuggest doesn't appear to have been setup correctly.
Please look at the output of the debug console (ctrl+``) for more information.
Traceback (most recent call last):
  File "/home/partisanyc/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/commands/idecommands.py", line 103, in run
    shutil.copy(nimsuggest_src_exe, exe_path)
  File "./shutil.py", line 227, in copy
  File "./shutil.py", line 109, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqj98a4/nimsuggest/nimsuggest'`

**Comment by Varriount** [comment] 2016-02-20 18:15
Duplicate of #61

**Closed by Varriount** 2016-02-20 18:15 UTC
